repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=10000']  # 10MB limit
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: ['--py39-plus']

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3
        args: ['--line-length=88']

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length=88"]

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==24.2.6, flake8-docstrings==1.7.0]
        args: ["--max-line-length=88", "--ignore=E501,W503,D100,D101,D102,D103,D104,D105,D106,D107,D401,D205,D202"]

-   repo: https://github.com/pycqa/bandit
    rev: 1.8.4
    hooks:
    -   id: bandit
        args: ["-r", "executive_orders_pdf/"]
        exclude: ^tests/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML, types-aiofiles]
        args: [--ignore-missing-imports, --no-strict-optional, --disable-error-code=return-value]
        exclude: ^(tests/|examples/)
