name: Download and Merge PDFs

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  download-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Cache downloaded PDFs
      uses: actions/cache@v2
      with:
        path: downloaded_pdfs
        key: ${{ runner.os }}-pdfs-${{ env.NOW }}
        restore-keys: |
          ${{ runner.os }}-pdfs-

    - name: Run download and merge script
      run: |
        python main.py "https://www.federalregister.gov/presidential-documents/executive-orders/donald-trump/2025" --output combined_document.pdf --download-dir downloaded_pdfs

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add combined_document.pdf
        git commit -m 'Automated update of combined_document.pdf'
        git push
